# -*- coding: utf-8 -*-
"""Crime-rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luz9sYPy3-8Wqyijn1BPG7xXUswl9WqT
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
df = pd.read_csv('crime.csv')
print(df.columns)

import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score, mean_squared_error,r2_score, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor

print("UNIQUE STATES/UT:\n\n",df['STATE/UT'].unique())

print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum)

df.rename(columns={
    "STATE/UT":"State",
    "YEAR":"Year",
    "Total IPC crime" : "Crime_count"
    },inplace=True)

df['STATE']=df['State'].str.strip()
print(df['State'])

df=df[['State','Year','MURDER',]]
df

df.tail(100)

ax=sns.countplot(x='MURDER',hue='State',data=df,palette='Set1')
for p in ax.patches:
  ax.annotate(f'\n{p.get_height()}',(p.get_x()+0.9,p.get_height()+100),ha='center',va='top',color='black',size=15)
  plt.show()

import matplotlib.pyplot as plt

crime_by_state = df.groupby('State')['MURDER'].sum().sort_values(ascending=False)

plt.figure(figsize=(15, 8))
sns.barplot(x=crime_by_state.index, y=crime_by_state.values, palette='Set1')

plt.xlabel('State/UT', fontsize=12)
plt.ylabel('Total Murder Count', fontsize=12)
plt.title('Total Murder Count by State/UT', fontsize=14)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
crime_by_state = df.groupby('State')['MURDER'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 20))
# Use crime_by_state.index for the labels
plt.pie(crime_by_state.values, labels=crime_by_state.index, autopct='%1.1f%%', startangle=140)
plt.title('Crime Distribution Across States (2001-2012)',fontsize=16)
plt.axis('equal')
plt.show()